### ISSUE TITLE
Could not resolve host: mydomain@dev.azure.com

### ISSUE THREAD

**Issue by robinhalabicki** [swellaby/vsts-mirror-git-repository#108]
I am unable to connect to the devops, removed my actual domain for "mydomain".   The destinationGitRepo variable is a copy paste from the DevOps Clone:
      destinationGitRepositoryUri: 'https://mydomain@dev.azure.com/mydomain/test1/_git/test1'

The Repo "test1" exists in devops.   The repo Intranet exists in Github

```

Output
Starting: mirrorgitrepositoryvststask
==============================================================================
Task         : Mirror Git Repository
Description  : A straightforward utility to mirror one Git repository to another location
Version      : 1.1.12
Author       : Swellaby
Help         : [More Information](https://github.com/swellaby/vsts-mirror-git-repository)
==============================================================================
/usr/bin/git -c http.sslVerify=false clone --mirror https://gitPAT@github.com/mydomain/Intranet.git Intranet.git
Cloning into bare repository 'Intranet.git'...
/usr/bin/git -c http.sslVerify=false -C Intranet.git push --mirror https://AzurePAT@mydomain@dev.azure.com/valuepartnersinvestments/test1/_git/test1
fatal: unable to access 'https://mydomain@dev.azure.com/mydomain/test1/_git/test1/': Could not resolve host: mydomain@dev.azure.com
##[error]Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by robinhalabicki** [comment]
![image](https://user-images.githubusercontent.com/22157886/130514195-bbbaee7e-3ceb-4d89-bd39-9136cbd30a07.png)
My PAT DevOps privs

**Comment by calebcartwright** [comment]
Suspect this is a duplicate of #105. Could you please try removing the org name from the userinfo component of the git slug? (i.e. use `https://dev.azure.com/your-org/your-project/_git/your-repo` instead of `https://**your-org@**dev.azure.com/your-org/your-project/_git/your-repo`

**Comment by robinhalabicki** [comment]
fatal: could not read Password for 'https://GitPAT@dev.azure.com': terminal prompts disabled

**Comment by robinhalabicki** [comment]
![image](https://user-images.githubusercontent.com/22157886/130626364-b92fb335-da16-4a78-a70d-58e4bf9c0bd3.png)

security in DevOps Pipeline

**Comment by calebcartwright** [comment]
I gather that you've been trying several different iterations, but it's still a little difficult to follow as your most recent comments indicate the opposite source/target as your issue description

I've just run a few tests, mirroring both to/from Azure DevOps and GitHub and have confirmed there's nothing wrong with the extension. As such, any issue you are experiencing is almost certainly related to how you've configured your task.

Your task configuration should look something like this, assuming Azure DevOps as the source and GitHub as the target as indicated in the last comment:

![image](https://user-images.githubusercontent.com/13042488/131232882-3f706c9c-2ef1-43f1-92c7-b24cb5bafdc3.png)

or with pipeline-as-code
```yaml
steps:
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/swellaby/OpenSource/_git/mirror1'
    sourceGitRepositoryPersonalAccessToken: '$(azureDevOpsPat)'
    destinationGitRepositoryUri: 'https://github.com/calebcartwright/azp-mirror-test'
    destinationGitRepositoryPersonalAccessToken: '$(gitHubPat)'
```

Make sure you have the right variables mapped to the right source control hosts in the task config, and that the variables have the correct, respective values. The `terminal prompts disabled` stems from missing or invalid auth info being provided to git, and git being unable to prompt for the password as it would in the interactive mode on your local machine.
