### ISSUE TITLE
Unable to Mirror git project in Azure Devops with option "Use new URL: https://dev.azure.com..."

### ISSUE THREAD

**Issue by tofindoutsysadmin** [swellaby/vsts-mirror-git-repository#124]
## Environment Details
* **Pipeline**
  * [x] Build
* **Agent Type**
    
  * [x] Hosted Agent
* **Agent OS**
  * [x] Linux (Image: ubuntu-latest:  Ubuntu 22.04.1)
* **Agent Tool Versions**
    
  * **git version**: **2.39.1**

* **Mirror Task Configuration**
  * **Mirror Git Repo Task version**: 1.1.12
  * **Mirror Source Repo System**
    * [X] Azure DevOps (formerly VSTS)
  * [x] Using PAT for Mirror Source Repo
  * [ ] Mirror Source Repo is Public
  * [x] Using SSL Verification on Mirror Source Repo
  * **Mirror Destination Repo System**
    * [x] GitHub
  * [x] Using PAT for Mirror Destination Repo
  * [ ] Mirror Destination Repo is Public
  * [x] Using SSL Verification on Mirror Destination Repo
  

## Description

Selected option to "Use new URL: https;//dev.azure.com/<mycompany>" it fails to Mirror our repositories. 
![image](https://user-images.githubusercontent.com/119297577/214545646-471d3441-49b5-447d-aa91-5b74d7b3fdc3.png)

`yml` looks like this:
```
trigger:
- '*'

# Also trigger on other repositories that are significant
resources:
  repositories:
    - repository: Repo
      type: git
      name: Project/Repo
      trigger:
      - '*'
  # Additional repository triggers  

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo $(Build.SourceBranchName)
# - script: echo $(Build.SourceBranch)
# - script: echo $(Build.Repository.Uri)
# - script: echo $(Build.Repository.Name)

- task: mirror-git-repository-vsts-task@1
  displayName: 'Mirroring'
  inputs:
    sourceGitRepositoryUri: $(Build.Repository.Uri)
    sourceGitRepositoryPersonalAccessToken: $(AzureDevopPAT)
    sourceVerifySSLCertificate: true
    destinationGitRepositoryUri: 'https://github.com/MyCompany/$(Build.Repository.Name)'
    destinationGitRepositoryPersonalAccessToken: '$(GitHubPAT)'
    destinationVerifySSLCertificate: true
```

## Log Output
```
Starting: Mirroring
==============================================================================
Task         : Mirror Git Repository
Description  : A straightforward utility to mirror one Git repository to another location
Version      : 1.1.12
Author       : Swellaby
Help         : [More Information](https://github.com/swellaby/vsts-mirror-git-repository)
==============================================================================
/usr/bin/git -c http.sslVerify=true clone --mirror [https://***@myCompany@dev.azure.com/myCompany/Project/_git/Repo](https://***%40myCompany@dev.azure.com/myCompany/Project/_git/Repo) Repo.git
Cloning into bare repository 'Repo.git'...
fatal: unable to access 'https://myCompany@dev.azure.com/myCompany/Project/_git/Repo/': URL using bad/illegal format or missing URL
##[error]Error: The process '/usr/bin/git' failed with exit code 128
Finishing: Mirroring
```
