### ISSUE TITLE
Yaml Docs

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/vsts-mirror-git-repository#23]
Given the emphasis Azure DevOps is placing on yaml-defined pipelines, we should update our docs to include usage from yaml as well as the visual designer

**Comment by calebcartwright** [comment]
Hi @mfkl - honestly I don't know. We're still personally primarily using the Visual Designer based Azure Pipelines so we haven't done much with the YAML configurations yet. 

I would _assume_ that the YAML engine supports 3rd party tasks like our mirror git repo task, but we haven't tested yet.

// cc @traviskosarek

**Comment by calebcartwright** [comment]
@mfkl - you can use a configuration like the below in your yaml file to use the mirror git repo task. Obviously replace the example values below with your respective mirror source/destination repos, etc.

```
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://github.com/swellaby/vsts-mirror-git-repository.git'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://dev.azure.com/swellaby/OpenSource/_git/mirror2'
    destinationGitRepositoryPersonalAccessToken: '$(destVar)'
    destinationVerifySSLCertificate: true
```
