### ISSUE TITLE
support multiple mirror tasks in same job with same source repository name

### ISSUE THREAD

**Issue by thebeautiful** [swellaby/vsts-mirror-git-repository#51]
I'm trying to mirror 2 separate git-repo's in one stage, one job, two tasks. Both git-repo's have the same original name, but live in 2 different organizations. Destination names are different of course.
I'm getting an error "fatal: destination path `xyz` already exists and is not an empty directory".

Workaround: spreading the two tasks on 2 different jobs keeps it apart.

**Comment by calebcartwright** [comment]
hey @thebeautiful, thanks for reaching out. The behavior you are experiencing is "expected" with the current version, because of the way the source repo is cloned into the local workspace. 

One enhancement I could see that would support your scenario would be a new input field in the task that would allow you to specify the repo directory for the clone. 

Assuming we called the new input something like `sourceGitRepositoryDirectory`:
```yml
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://github.com/org1/foo.git'
    sourceGitRepositoryDirectory: 'foo-1',
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://dev.azure.com/myorg/myproject/_git/mirror1'
    destinationGitRepositoryPersonalAccessToken: '$(destVar)'

- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://github.com/second-org/foo.git'
    sourceGitRepositoryDirectory: 'foo-2',
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://dev.azure.com/myorg/myproject/_git/mirror2'
    destinationGitRepositoryPersonalAccessToken: '$(destVar)'
```

cc @traviskosarek - thoughts?
